### ISSUE TITLE
Home Assistant Component

### ISSUE THREAD

**Issue by markusressel** [Phunkafizer/RaspyRFM#1]
Hey there,

I am in the beginning of setting up Home Assistant on a Raspberry Pi and would like to include your project as a component so Home Assistant is able to receive network signals via UDP (from apps like PowerSwitch), convert them to 433 MHz signals and send them with your 433MHz module.

There is no license mentioned in this repo.
If you don't have plans to do this youself I want to ask if I am allowed to use your code and make a Home Assistant custom component out of it. If there is a way to include your project as a dependency in a custom component of mine that would be even better as I would not need to maintain any changes you make.

Greetings,
Markus Ressel

**Comment by Phunkafizer** [comment]
Added licence
